export const areas = [
  //#region Leazas
  {
    id: "leazas_castle",
    name: "Leazas Castle",
    x: 4197,
    y: 1090,
    type: "city",
  },
  { id: "leazas_wes", name: "Wes", x: 4323, y: 806, type: "city" },
  { id: "leazas_ponara", name: "Ponara", x: 4258, y: 686, type: "city" },
  { id: "leazas_prettiria", name: "Prettiria", x: 4077, y: 872, type: "city" },
  { id: "leazas_alan", name: "Alan", x: 4058, y: 654, type: "city" },
  { id: "leazas_scale", name: "Scale", x: 3814, y: 889, type: "city" },
  { id: "leazas_north", name: "North", x: 3970, y: 1129, type: "city" },
  { id: "leazas_maunes", name: "Maunes", x: 3634, y: 1060, type: "city" },
  { id: "leazas_rich", name: "Rich", x: 3346, y: 1167, type: "city" },
  { id: "leazas_poor", name: "Poor", x: 3493, y: 1212, type: "city" },
  { id: "leazas_oaks", name: "Oaks", x: 4466, y: 1275, type: "city" },
  { id: "leazas_ys", name: "Ys", x: 4424, y: 1110, type: "city" },
  { id: "leazas_baranchi", name: "Baranchi", x: 4446, y: 967, type: "city" },
  { id: "leazas_south", name: "South", x: 4190, y: 1280, type: "city" },
  { id: "leazas_oc", name: "Oc", x: 3958, y: 1236, type: "city" },
  {
    id: "leazas_parapara_fortress",
    name: "Parapara Fortress",
    x: 3242,
    y: 1231,
    type: "city",
  },
  {
    id: "leazas_thieves_dungeon",
    name: "Thieves' Dungeon",
    x: 4106,
    y: 1128,
    type: "dungeon",
  },
  {
    id: "leazas_monsters_cave",
    name: "Monster's Cave",
    x: 3748,
    y: 1181,
    type: "dungeon",
  },
  {
    id: "leazas_isolated_shrine_island",
    name: "Isolated Shrine Island",
    x: 4077,
    y: 425,
    type: "dungeon",
  },
  //#endregion Leazas

  //#region Free Cities
  { id: "freecities_the_o", name: "The O", x: 3933, y: 1383, type: "city" },
  {
    id: "freecities_rockearth",
    name: "Rockearth",
    x: 3402,
    y: 1346,
    type: "city",
  },
  { id: "freecities_ice", name: "Ice", x: 3443, y: 1538, type: "city" },
  { id: "freecities_l_zile", name: "L Zile", x: 3590, y: 1517, type: "city" },
  { id: "freecities_red", name: "Red", x: 3736, y: 1469, type: "city" },
  { id: "freecities_m_land", name: "M Land", x: 4006, y: 1548, type: "city" },
  { id: "freecities_hanna", name: "Hanna", x: 4282, y: 1480, type: "city" },
  {
    id: "freecities_portugal",
    name: "Portugal",
    x: 4292,
    y: 1724,
    type: "city",
  },
  {
    id: "freecities_toushin_city",
    name: "Toushin City",
    x: 4049,
    y: 1779,
    type: "city",
  },
  { id: "freecities_mars", name: "Mars", x: 3649, y: 1934, type: "city" },
  { id: "freecities_custom", name: "Custom", x: 3718, y: 1658, type: "city" },
  {
    id: "freecities_diphtheria",
    name: "Diphtheria",
    x: 3401,
    y: 1650,
    type: "city",
  },
  {
    id: "freecities_shangrila",
    name: "Shangri-La",
    x: 2817,
    y: 981,
    type: "city",
  },
  {
    id: "freecities_titi_lake",
    name: "Titi Lake",
    x: 3583,
    y: 1384,
    type: "dungeon",
  },
  {
    id: "freecities_dangerous_hole",
    name: "Dangerous Hole",
    x: 3864,
    y: 1696,
    type: "dungeon",
  },
  {
    id: "freecities_uncurse_dungeon",
    name: "Uncurse Dungeon",
    x: 4409,
    y: 1548,
    type: "dungeon",
  },
  {
    id: "freecities_peach_blossom_spring",
    name: "Peach Blossom Spring",
    x: 4104,
    y: 1898,
    type: "dungeon",
  },
  {
    id: "freecities_hyper_building",
    name: "Hyper Building",
    x: 3821,
    y: 1549,
    type: "dungeon",
  },
  //#endregion Free Cities

  //#region JAPAN
  { id: "japan_nagasaki", name: "Nagasaki", x: 4404, y: 1824, type: "city" },
  { id: "japan_osaka", name: "Osaka", x: 4600, y: 1676, type: "city" },
  { id: "japan_sado", name: "Sado", x: 4765, y: 1281, type: "city" },
  {
    id: "japan_orochis_pit",
    name: "Orochi's Pit",
    x: 4400,
    y: 1906,
    type: "dungeon",
  },
  //#endregion JAPAN

  //AL
  {
    id: "al_temple_al_hq",
    name: "Temple AL HQ",
    x: 3200,
    y: 1722,
    type: "city",
  },

  //#region Helman
  { id: "helman_volgo_z", name: "Volgo Z", x: 3116, y: 928, type: "city" },
  { id: "helman_log_b", name: "Log B", x: 3318, y: 751, type: "city" },
  { id: "helman_log_a", name: "Log A", x: 3529, y: 636, type: "city" },
  {
    id: "helman_vladivostok",
    name: "Vladivostok",
    x: 3478,
    y: 449,
    type: "city",
  },
  { id: "helman_golak", name: "Golak", x: 3327, y: 543, type: "city" },
  { id: "helman_siberia", name: "Siberia", x: 3052, y: 441, type: "city" },
  { id: "helman_rosesgrad", name: "Rosesgrad", x: 2939, y: 557, type: "city" },
  { id: "helman_archgrad", name: "Archgrad", x: 3134, y: 650, type: "city" },
  {
    id: "helman_ancient_ruins",
    name: "Ancient Ruins",
    x: 3214,
    y: 585,
    type: "city",
  },
  { id: "helman_sudori_10", name: "Sudori 10", x: 2625, y: 479, type: "city" },
  { id: "helman_path", name: "Path", x: 2522, y: 373, type: "city" },
  { id: "helman_micrograd", name: "Micrograd", x: 2476, y: 558, type: "city" },
  { id: "helman_pawn", name: "Pawn", x: 2788, y: 666, type: "city" },
  { id: "helman_cossack", name: "Cossack", x: 3001, y: 759, type: "city" },
  { id: "helman_sudori_13", name: "Sudori 13", x: 2705, y: 814, type: "city" },
  { id: "helman_sudori_17", name: "Sudori 17", x: 2316, y: 785, type: "city" },
  { id: "helman_parnas", name: "Parnas", x: 2062, y: 655, type: "city" },
  {
    id: "helman_laurengrad",
    name: "Laurengrad",
    x: 1955,
    y: 503,
    type: "city",
  },
  { id: "helman_laborie", name: "Laborie", x: 1934, y: 801, type: "city" },
  { id: "helman_walkland", name: "Walkland", x: 1680, y: 458, type: "city" },
  { id: "helman_icoma", name: "Icoma", x: 1878, y: 276, type: "city" },
  {
    id: "helman_great_wall_a",
    name: "Great Wall of Helman A",
    x: 1534,
    y: 104,
    type: "city",
  },
  {
    id: "helman_great_wall_b",
    name: "Great Wall of Helman B",
    x: 1445,
    y: 565,
    type: "city",
  },
  {
    id: "helman_great_wall_c",
    name: "Great Wall of Helman C",
    x: 1694,
    y: 786,
    type: "city",
  },
  { id: "helman_lang_bau", name: "Lang Bau", x: 2323, y: 569, type: "city" },
  {
    id: "helman_giant_battleship",
    name: "Giant Battleship",
    x: 2270,
    y: 229,
    type: "dungeon",
  },
  {
    id: "helman_stone_cutter_dungeon",
    name: "Stone-Cutter Dungeon",
    x: 1882,
    y: 96,
    type: "dungeon",
  },
  {
    id: "helman_mt_salen",
    name: "Mt. Salen",
    x: 1578,
    y: 317,
    type: "dungeon",
  },
  {
    id: "helman_snow_dungeon",
    name: "Snow Dungeon",
    x: 2816,
    y: 278,
    type: "dungeon",
  },
  {
    id: "helman_ho_ragas_tower",
    name: "Ho Raga's Tower",
    x: 3835,
    y: 141,
    type: "dungeon",
  },
  {
    id: "helman_thieves_hideout",
    name: "Thieves' Hideout",
    x: 3354,
    y: 409,
    type: "dungeon",
  },
  {
    id: "helman_natural_foes_dungeon",
    name: "Natural Foe's Dungeon",
    x: 2954,
    y: 848,
    type: "dungeon",
  },
  {
    id: "helman_summits_mouth",
    name: "Summit's Mouth",
    x: 3658,
    y: 752,
    type: "dungeon",
  },
  {
    id: "helman_kalar_forest",
    name: "Kalar Forest",
    x: 1873,
    y: 1060,
    type: "dungeon",
  },

  //#endregion Helman

  //#region Zeth
  {
    id: "zeth_adams_fortress",
    name: "Adam's Fortress",
    x: 3138,
    y: 1274,
    type: "city",
  },
  { id: "zeth_sabasaba", name: "Sabasaba", x: 2819, y: 1244, type: "city" },
  { id: "zeth_nagarmaule", name: "Nagarmaule", x: 2451, y: 1255, type: "city" },
  {
    id: "zeth_nagis_tower",
    name: "Nagi's Tower",
    x: 2451,
    y: 1440,
    type: "city",
  },
  {
    id: "zeth_magics_tower",
    name: "Magic's Tower",
    x: 2489,
    y: 1615,
    type: "city",
  },
  {
    id: "zeth_papayas_tower",
    name: "Papaya's Tower",
    x: 2225,
    y: 1612,
    type: "city",
  },
  {
    id: "zeth_chizukos_tower",
    name: "Chizuko's Tower",
    x: 2232,
    y: 1421,
    type: "city",
  },
  { id: "zeth_parityoran", name: "Parityoran", x: 2105, y: 1341, type: "city" },
  {
    id: "zeth_maginot_line_a",
    name: "Maginot Line A",
    x: 1892,
    y: 1424,
    type: "city",
  },
  { id: "zeth_marc", name: "Marc", x: 2388, y: 1785, type: "city" },
  { id: "zeth_palace", name: "Zeth Palace", x: 2351, y: 1524, type: "city" },
  { id: "zeth_italia", name: "Italia", x: 2718, y: 1460, type: "city" },
  { id: "zeth_tape", name: "Tape", x: 2793, y: 1665, type: "city" },
  { id: "zeth_old", name: "Old Zeth", x: 2655, y: 1790, type: "city" },
  { id: "zeth_bath", name: "Bath", x: 2716, y: 1946, type: "city" },
  {
    id: "zeth_amber_castle",
    name: "Amber Castle",
    x: 2482,
    y: 1908,
    type: "city",
  },
  {
    id: "zeth_maginot_line_b",
    name: "Maginot Line B",
    x: 2126,
    y: 1948,
    type: "city",
  },
  { id: "zeth_ardennes", name: "Ardennes", x: 2236, y: 1780, type: "city" },
  {
    id: "zeth_holy_gals_dungeon",
    name: "Holy Gal's Dungeon",
    x: 3025,
    y: 1365,
    type: "dungeon",
  },
  {
    id: "zeth_rising_dragon_mountain",
    name: "Rising Dragon Mountain",
    x: 2084,
    y: 1124,
    type: "dungeon",
  },
  {
    id: "zeth_green_village",
    name: "Green Village",
    x: 1742,
    y: 1169,
    type: "dungeon",
  },
  //#endregion Zeth

  //#region Monster Realm
  //#endregion Monster Realm
];
